services:
  - type: web
    name: aac-strava-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: ./backend
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health